=== YanaV267/JWD_Task3/src/main/resources/data/cards.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/postal-cards"
        xmlns:tns="http://www.example.com/postal-cards"
        elementFormDefault="qualified">

    <element name="postal-cards">
        <complexType>
            <sequence>
                <element ref="tns:postal-card" minOccurs="3" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <element name="postal-card" type="tns:Card" abstract="true"/>
    <element name="greeting-card" type="tns:GreetingCard" substitutionGroup="tns:postal-card"/>
    <element name="promotional-card" type="tns:PromotionalCard" substitutionGroup="tns:postal-card"/>

    <complexType name="Card">
        <sequence>
            <element name="theme" type="tns:ThemeType"/>
            <element name="origin-country" type="string"/>
            <element name="year" type="gYear"/>
            <element name="author" type="string" default="unknown"/>
            <element name="sent" type="boolean" default="false"/>
            <element name="destination-address" type="tns:Address"/>
        </sequence>
        <attribute name="id" type="tns:CardId" use="required"/>
        <attribute name="title" type="string" use="optional"/>
    </complexType>

    <complexType name="GreetingCard">
        <complexContent>
            <extension base="tns:Card">
                <sequence>
                    <element name="holiday" type="tns:Holiday"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="PromotionalCard">
        <complexContent>
            <extension base="tns:Card">
                <sequence>
                    <element name="company-name" type="string"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <simpleType name="CardId">
        <restriction base="ID">
            <pattern value="card-\d{1,10}"/>
        </restriction>
    </simpleType>

    <simpleType name="ThemeType">
        <restriction base="string">
            <enumeration value="scenery"/>
            <enumeration value="animal"/>
            <enumeration value="people"/>
            <enumeration value="religion"/>
            <enumeration value="history"/>
            <enumeration value="sport"/>
            <enumeration value="architecture"/>
            <enumeration value="music"/>
            <enumeration value="art"/>
        </restriction>
    </simpleType>

    <simpleType name="Holiday">
        <restriction base="string">
            <enumeration value="new-year"/>
            <enumeration value="christmas"/>
            <enumeration value="birthday"/>
            <enumeration value="wedding"/>
        </restriction>
    </simpleType>

    <complexType name="Address">
        <sequence>
            <element name="country" type="string"/>
            <element name="town" type="string"/>
            <element name="street" type="tns:Street"/>
        </sequence>
    </complexType>

    <simpleType name="Street">
        <restriction base="string">
            <pattern value="[A-ZА-Я].[а-яa-z]{2,30}, \d{1,4}(-[\dA-Z])?(-\d{1,3})?"/>
        </restriction>
    </simpleType>
</schema>

=== YanaV267/JWD_Task3/src/test/resources/data/cards.xml
<?xml version="1.0" encoding="UTF-8"?>
<postal-cards xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xmlns="http://www.example.com/postal-cards"
             xsi:schemaLocation="http://www.example.com/postal-cards cards.xsd">
    <greeting-card id="card-1" title="Летняя идиллия">
        <theme>scenery</theme>
        <origin-country>Russia</origin-country>
        <year>2013</year>
        <author>Шукшин</author>
        <sent>true</sent>
        <destination-address>
            <country>Russia</country>
            <town>Moscow</town>
            <street>Ленина, 189-514</street>
        </destination-address>
        <holiday>birthday</holiday>
    </greeting-card>
    <greeting-card id="card-2">
        <theme>art</theme>
        <origin-country>Ukraine</origin-country>
        <year>1992</year>
        <author>Алмакова</author>
        <sent>false</sent>
        <destination-address>
            <country>Germany</country>
            <town>Dresden</town>
            <street>Plattleite, 9-A-21</street>
        </destination-address>
        <holiday>new-year</holiday>
    </greeting-card>
    <promotional-card id="card-3">
        <theme>music</theme>
        <origin-country>Belarus</origin-country>
        <year>2018</year>
        <author>Соболев</author>
        <sent>true</sent>
        <destination-address>
            <country>Poland</country>
            <town>Gdanks</town>
            <street>Lanowa, 19-3</street>
        </destination-address>
        <company-name>StarStrike</company-name>
    </promotional-card>
    <promotional-card id="card-4">
        <theme>art</theme>
        <origin-country>Belarus</origin-country>
        <year>2013</year>
        <author>Емельянов</author>
        <sent>false</sent>
        <destination-address>
            <country>Lithuania</country>
            <town>Vilnus</town>
            <street>Kirtumy, 39-1</street>
        </destination-address>
        <company-name>Olivian</company-name>
    </promotional-card>
    <greeting-card id="card-5" title="Sonnenaufgang">
        <theme>religion</theme>
        <origin-country>Germany</origin-country>
        <year>1809</year>
        <author>Swolan</author>
        <sent>true</sent>
        <destination-address>
            <country>Germany</country>
            <town>Berlin</town>
            <street>Strew, 72-C-2</street>
        </destination-address>
        <holiday>new-year</holiday>
    </greeting-card>
    <promotional-card id="card-6">
        <theme>animal</theme>
        <origin-country>Russia</origin-country>
        <year>2010</year>
        <author>Антонова</author>
        <sent>true</sent>
        <destination-address>
            <country>Belarus</country>
            <town>Витебск</town>
            <street>Гагарина, 43-1-89</street>
        </destination-address>
        <company-name>Bellagio</company-name>
    </promotional-card>
    <greeting-card title="СемьЯ" id="card-7">
        <theme>animal</theme>
        <origin-country>Russia</origin-country>
        <year>2002</year>
        <author>Леонов</author>
        <sent>true</sent>
        <destination-address>
            <country>Italy</country>
            <town>Monaco</town>
            <street>Ligure, 2-A</street>
        </destination-address>
        <holiday>birthday</holiday>
    </greeting-card>
    <greeting-card id="card-8">
        <theme>art</theme>
        <origin-country>Ukraine</origin-country>
        <year>1992</year>
        <author>Алмакова</author>
        <sent>false</sent>
        <destination-address>
            <country>Germany</country>
            <town>Dresden</town>
            <street>Plattleite, 9-A-21</street>
        </destination-address>
        <holiday>new-year</holiday>
    </greeting-card>
    <greeting-card id="card-9" title="Warriors">
        <theme>history</theme>
        <origin-country>Latvia</origin-country>
        <year>1987</year>
        <author>Савельев</author>
        <sent>true</sent>
        <destination-address>
            <country>Belarus</country>
            <town>Минск</town>
            <street>Победителей, 124-78</street>
        </destination-address>
        <holiday>wedding</holiday>
    </greeting-card>
    <promotional-card id="card-10">
        <theme>music</theme>
        <origin-country>Belarus</origin-country>
        <year>2018</year>
        <author>Соболев</author>
        <sent>true</sent>
        <destination-address>
            <country>Poland</country>
            <town>Gdanks</town>
            <street>Lanowa, 19-3</street>
        </destination-address>
        <company-name>StarStrike</company-name>
    </promotional-card>
    <promotional-card id="card-11" title="wild life">
        <theme>animal</theme>
        <origin-country>Belarus</origin-country>
        <year>2017</year>
        <author>Ульянова</author>
        <sent>true</sent>
        <destination-address>
            <country>Germany</country>
            <town>Berlin</town>
            <street>Hauptstrasse, 5-14</street>
        </destination-address>
        <company-name>SeasonS</company-name>
    </promotional-card>
    <greeting-card id="card-12">
        <theme>art</theme>
        <origin-country>Belarus</origin-country>
        <year>2007</year>
        <author>Добрушевский</author>
        <sent>true</sent>
        <destination-address>
            <country>Germany</country>
            <town>Dresden</town>
            <street>Plattleite, 9-A-21</street>
        </destination-address>
        <holiday>new-year</holiday>
    </greeting-card>
    <promotional-card title="United" id="card-13">
        <theme>people</theme>
        <origin-country>Poland</origin-country>
        <year>2018</year>
        <author>Plotnikowski</author>
        <sent>true</sent>
        <destination-address>
            <country>Poland</country>
            <town>Wroclaw</town>
            <street>Laskowize, 48</street>
        </destination-address>
        <company-name>DobraZ</company-name>
    </promotional-card>
    <greeting-card id="card-14">
        <theme>music</theme>
        <origin-country>Ukraine</origin-country>
        <year>2019</year>
        <author>Алмакова</author>
        <sent>false</sent>
        <destination-address>
            <country>Germany</country>
            <town>Dresden</town>
            <street>Hauptstrasse, 21</street>
        </destination-address>
        <holiday>wedding</holiday>
    </greeting-card>
    <promotional-card id="card-15">
        <theme>art</theme>
        <origin-country>Kazakhstan</origin-country>
        <year>2018</year>
        <author>Абишев</author>
        <sent>true</sent>
        <destination-address>
            <country>Russia</country>
            <town>Иркутск</town>
            <street>Первомайская, 98-43</street>
        </destination-address>
        <company-name>Pozdravitel</company-name>
    </promotional-card>
    <greeting-card id="card-16">
        <theme>religion</theme>
        <origin-country>Ukraine</origin-country>
        <year>2019</year>
        <author>Алмакова</author>
        <sent>true</sent>
        <destination-address>
            <country>Russia</country>
            <town>Екатеринбург</town>
            <street>Машерова, 11-A-8</street>
        </destination-address>
        <holiday>christmas</holiday>
    </greeting-card>
</postal-cards>
